// 音频文件映射 - 自动生成
// 包含所有74个词汇的音频文件映射

const AUDIO_FILE_MAPPING = {
    "api": "api.wav",
    "accuracy": "accuracy.wav",
    "activation function": "activation_function.wav",
    "algorithm": "algorithm.wav",
    "architecture": "architecture.wav",
    "array": "array.wav",
    "artificial intelligence": "artificial_intelligence.wav",
    "backpropagation": "backpropagation.wav",
    "bandwidth": "bandwidth.wav",
    "binary tree": "binary_tree.wav",
    "cdn": "cdn.wav",
    "class": "class.wav",
    "client": "client.wav",
    "cloud computing": "cloud_computing.wav",
    "compiler": "compiler.wav",
    "computer vision": "computer_vision.wav",
    "convolutional neural network": "convolutional_neural_network.wav",
    "cross-validation": "cross-validation.wav",
    "dns": "dns.wav",
    "data structure": "data_structure.wav",
    "database": "database.wav",
    "deadlock": "deadlock.wav",
    "debugging": "debugging.wav",
    "deep learning": "deep_learning.wav",
    "dimensionality reduction": "dimensionality_reduction.wav",
    "encryption": "encryption.wav",
    "exception": "exception.wav",
    "feature": "feature.wav",
    "firewall": "firewall.wav",
    "framework": "framework.wav",
    "function": "function.wav",
    "gradient descent": "gradient_descent.wav",
    "http": "http.wav",
    "https": "https.wav",
    "hash table": "hash_table.wav",
    "ip address": "ip_address.wav",
    "index": "index.wav",
    "inheritance": "inheritance.wav",
    "internet": "internet.wav",
    "interpreter": "interpreter.wav",
    "iot": "iot.wav",
    "latency": "latency.wav",
    "library": "library.wav",
    "load balancer": "load_balancer.wav",
    "loop": "loop.wav",
    "machine learning": "machine_learning.wav",
    "natural language processing": "natural_language_processing.wav",
    "network": "network.wav",
    "neural network": "neural_network.wav",
    "neuron": "neuron.wav",
    "normalization": "normalization.wav",
    "object": "object.wav",
    "overfitting": "overfitting.wav",
    "polymorphism": "polymorphism.wav",
    "process": "process.wav",
    "protocol": "protocol.wav",
    "query": "query.wav",
    "recurrent neural network": "recurrent_neural_network.wav",
    "recursion": "recursion.wav",
    "refactoring": "refactoring.wav",
    "repository": "repository.wav",
    "router": "router.wav",
    "ssl/tls": "ssl_tls.wav",
    "scalability": "scalability.wav",
    "server": "server.wav",
    "space complexity": "space_complexity.wav",
    "syntax": "syntax.wav",
    "thread": "thread.wav",
    "time complexity": "time_complexity.wav",
    "training": "training.wav",
    "transformer": "transformer.wav",
    "vpn": "vpn.wav",
    "variable": "variable.wav",
    "version control": "version_control.wav",
};

// 导出映射
if (typeof module !== 'undefined' && module.exports) {
    module.exports = AUDIO_FILE_MAPPING;
} else {
    window.AUDIO_FILE_MAPPING = AUDIO_FILE_MAPPING;
}
